robotman:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: base_link__cuerpo
    pid: {p: 20000.0, i: 100, d: 50.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: cuerpo__cabeza
    pid: {p: 2000.0, i: 100, d: 50.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: cuerpo__brazo_derecho
    pid: {p: 2000.0, i: 100, d: 50.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: cuerpo__brazo_izquierdo
    pid: {p: 2000.0, i: 100, d: 50.0}
